### PR TITLE
Update mining and faq, add introduction

### PR DESCRIPTION
**Pull request by FedericoCeratto**

### CODE REVIEW

**Comment by bassosimone** [comment]
This issue seems related to this PR: https://github.com/ooni/probe/issues/1742

**Review by bassosimone — COMMENTED** [review]
Thank you for spearheading this important documentation revamp!

Here are some suggestions:

1. introduction.md: the title of the new post should also be "a gentle introduction to OONI"

2. introduction.md: note that the bullet list describing the ways in which we classify results do not render correctly on the website (try checking the preview)

3. website: I think the about and nettests section should have extra content that somehow gently steers the reader towards the faq, the glossary, and the new blog post

4. introduction.md: the new blog post should mention not only the faq but also the glossary

5. mining-ooni-data.md: maybe this could benefit from a link to introduction.md and to the faq and/or glossary at the beginning

6. website: make sure relevant places in the website link to mining-ooni-data.md

7. mining-ooni-data.md: in the rendered webpage there is a stray [fastpath] link

**Review by hellais — APPROVED** [review]
I have reviewed the PR and it looks great. I made some edits inside of both of the posts.

The edits were:
- Change the filename of the blog post
- Fix links to point to explorer.ooni.org (instead of `.io`)
- Add reference to the ooni/spec for the raw data formats
- Add links to the OONI API documentation
- Minor grammar edits

**Comment by bassosimone** [comment]
I am going to merge this PR, since (1) it's really _golden_, (2) it's really useful to have it since we can refer to it, (3) everyone who did review it was happy and provided improving edits, (4) if we need more edits we can add more later.

Thank you again @FedericoCeratto for taking the initiative here: this work really improves our docs!

**Pull request merged**
