### PR TITLE
Edited the various webpages of the OONI website

### PR DESCRIPTION
**Pull request by agrabeli**
This PR includes copy edits to all OONI webpages in order to update the information.

@hellais I'd like to bring 2 things to your attention:

1.  I'd very much appreciate it if you could please replace the drawing in the main landing page (how-ooni-works.png) with an image from the new Install page (showing the new OONI Probe mobile and desktop apps). 

2. As part of my review of and edits to the Risks documentation, I have deleted all reference to the use of anonymity software, as my understanding is that we no longer make use of it (i.e. we don't currently use onion services, and the new Psiphon test doesn't require installation of Psiphon). Is this accurate/reasonable?

### CODE REVIEW

**Comment by hellais** [comment]
>As part of my review of and edits to the Risks documentation, I have deleted all reference to the use of anonymity software, as my understanding is that we no longer make use of it (i.e. we don't currently use onion services, and the new Psiphon test doesn't require installation of Psiphon). Is this accurate/reasonable?

It is correct that this is currently the case with the mobile apps, however we do have circumvention tool tests in the desktop app. It is true that we don't require the installation of Psiphon to run those tests.

> I'd very much appreciate it if you could please replace the drawing in the main landing page (how-ooni-works.png) with an image from the new Install page (showing the new OONI Probe mobile and desktop apps).

Yes, I will look into this as part of merging the PR.

**Comment by hellais** [comment]
I added the requested images and also used this as an opportunity to do some improvements to the landing page as well, including implementing the new navbar.

@agrabeli please take a look and if it's OK we can merge.

**Comment by agrabeli** [comment]
Thank you @hellais , your changes look great! 

The only feedback for improvement that I have is to replace the OONI Explorer screenshot with a better quality/resolution one, like the one that is currently included on this page (https://ooni.org/images/ooni-explorer-screenshot@2x.png).

**Comment by hellais** [comment]
@agrabeli I fixed the ooni-explorer image and took note of your feedback for the navbar in this issue: https://github.com/ooni/ooni.org/issues/480.

**Comment by agrabeli** [comment]
Thank you @hellais for the review!

**Pull request merged**
