### PR TITLE
add a RiseupVPN test description

### PR DESCRIPTION
**Pull request by cyBerta**
https://github.com/ooni/probe-android/pull/393 is kind of depending on this PR, since it includes some strings containing a link to the test description. The link is shown in the GUI in the test detail activity to provide additional information.

### CODE REVIEW

**Comment by cyBerta** [comment]
@bassosimone @hellais This PR is the last dependency of https://github.com/ooni/probe-android/pull/393. We're exited to see the riseupvpn test in the ooni android client :) and would be happy to get some feedback if you think this PR is ok or needs changes.
Sorry, if you are the wrong persons to ping here.

**Comment by bassosimone** [comment]
@cyBerta We are excited as well! I am personally looking forward to adding more functionality to the test. I am thinking, for example, of pluggable transports.

As for who could review the new copy, let me also Cc: @agrabeli.

Thank you for your great work!

**Comment by agrabeli** [comment]
Thank you @cyBerta for writing a new RiseupVPN test, and thank you for the excellent test description!

I have reviewed the test description and shared some minor edits: https://github.com/ooni/ooni.org/pull/716/commits/ddaee1e36d44c6cd3fec43a8af32175bd56da0d9

I look forward to seeing this new test shipped as part of the OONI Probe apps. Thanks again! <3

**Comment by agrabeli** [comment]
@cyBerta We'd love to give you credit for writing this exciting new test! May we do so? If so, how would you like to be credited? Thanks!

**Comment by cyBerta** [comment]
Hi @agrabeli, thank you for reviewing the PR. You could give credits to the LEAP collective. Kwadronaut and me are involved there.

**Comment by agrabeli** [comment]
Thanks @cyBerta. I have added credits to the LEAP collective here: https://github.com/ooni/ooni.org/pull/716/commits/a17df784ae4769a9babc349e388120bdd126818b 

Is this OK, or would you like us to edit this?

Thanks again for your amazing work!

**Comment by cyBerta** [comment]
It's perfect, thanks. I didn't even think of adding credits before.

**Pull request merged**
